<?php

namespace common\models;

use Yii;
use yii2tech\ar\dynattribute\DynamicAttributeBehavior;

/**
 * This is the model class for table "url".
 *
 * @property int $id
 * @property string $route
 * @property string $suffix
 * @property int $type
 * @property string $seo
 * @property string $created_at
 * @property string $updated_at
 * @property int $is_deleted
 * @property string $title
 * @property string $description
 */
class Url extends \yii\db\ActiveRecord
{
    const TYPE_BRAND = 1;
    const TYPE_CATEGORY = 2;
    const TYPE_PRODUCT = 3;
    const TYPE_TAG = 4;
    const TYPE_VISIBLE = 0;

    public function behaviors()
    {
        return [
            'dynamicAttribute' => [
                'class' => DynamicAttributeBehavior::class,
                'storageAttribute' => 'seo', // field to store serialized attributes
                'dynamicAttributeDefaults' => [ // default values for the dynamic attributes
                    'title' => '',
                    'description' => '',
                ],
            ],
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'url';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['route', 'type'], 'required'],
            [['type', 'is_deleted'], 'integer'],
            [['seo'], 'string'],
            [['updated_at', 'created_at'], 'safe'],
            [['route'], 'string', 'max' => 255],
            [['suffix'], 'string', 'max' => 16],
            [['title', 'description'], 'string', 'max' => 255],
            [['route'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'route' => 'Route',
            'suffix' => 'Suffix',
            'type' => 'Type',
            'seo' => 'Seo',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'is_deleted' => 'Is Deleted',
        ];
    }
}
