<?php

namespace common\models;

use Yii;
use yii2tech\ar\dynattribute\DynamicAttributeBehavior;

/**
 * This is the model class for table "urls".
 *
 * @property int $id
 * @property string $route
 * @property string $suffix
 * @property int $type
 * @property string $seo
 * @property int $created_at
 * @property int $updated_at
 * @property int $deleted_at
 * @property int $is_deleted
 * @property string $title
 * @property string $description
 */
class Urls extends \yii\db\ActiveRecord
{
    const CATEGORY = 1;
    const PRODUCT = 2;
    const TAG = 3;
    const VISIBLE = 0;
    public function behaviors()
    {
        return [
            'dynamicAttribute' => [
                'class' => DynamicAttributeBehavior::class,
                'storageAttribute' => 'seo', // field to store serialized attributes
                'dynamicAttributeDefaults' => [ // default values for the dynamic attributes
                    'title' => '',
                    'description' => '',
                ],
            ],
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'urls';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['route', 'type', 'created_at'], 'required'],
            [['type', 'created_at', 'updated_at', 'deleted_at', 'is_deleted'], 'integer'],
            [['seo'], 'safe'],
            [['route'], 'string', 'max' => 255],
            [['suffix'], 'string', 'max' => 16],
            [['title','description'],'string','max' => 255],
            [['route'],'unique','message' => '{attribute} không được trùng.'],
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'route' => 'Đường dẫn',
            'suffix' => 'Suffix',
            'type' => 'Type',
            'seo' => 'Seo',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'is_deleted' => 'Is Deleted',
            'title' => 'Tiêu đề trang',
            'description' => 'Mô tả trang',
        ];
    }
}
